---
kind: pipeline
name: quality

platform:
  os: linux
  arch: amd64

steps:
- name: format
  pull: never
  image: patwie/clang-format:latest
  commands:
  - ./.ci/check.sh

- name: lint
  pull: never
  image: patwie/cpplint:latest
  commands:
  - cpplint --recursive .

---
kind: pipeline
name: CUDA 8.0

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: never
  image: patwie/cuda:8.0
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make

- name: test
  pull: never
  image: patwie/cuda:8.0
  commands:
  - ./build/test_cpu

depends_on:
- quality

---
kind: pipeline
name: CUDA 9.0

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: never
  image: patwie/cuda:9.0
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make

- name: test
  pull: never
  image: patwie/cuda:9.0
  commands:
  - ./build/test_cpu

depends_on:
- quality

---
kind: pipeline
name: CUDA 9.1

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: never
  image: patwie/cuda:9.1
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make

- name: test
  pull: never
  image: patwie/cuda:9.1
  commands:
  - ./build/test_cpu

depends_on:
- quality

---
kind: pipeline
name: CUDA 9.2

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: never
  image: patwie/cuda:9.2
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make

- name: test
  pull: never
  image: patwie/cuda:9.2
  commands:
  - ./build/test_cpu

depends_on:
- quality

---
kind: pipeline
name: CUDA 10.0

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: never
  image: patwie/cuda:10.0
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make

- name: test
  pull: never
  image: patwie/cuda:10.0
  commands:
  - ./build/test_cpu

depends_on:
- quality

---
kind: pipeline
name: CUDA 10.1

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: never
  image: patwie/cuda:10.1
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make

- name: test
  pull: never
  image: patwie/cuda:10.1
  commands:
  - ./build/test_cpu

depends_on:
- quality

---
kind: signature
hmac: 7d2643e4c55153be2ec8b9abff2231bd4b10f0be12de2308e98025346504d8c6

...
