---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: format
  pull: never
  image: patwie/clang-format:latest
  commands:
    - ./.ci/check.sh

- name: cpplint
  pull: never
  image: patwie/cpplint:latest
  commands:
    - cpplint --recursive .

- name: compile
  image: patwie/cuda:latest
  pull: never
  commands:
    - mkdir build
    - cd build
    - cmake ..
    - make


---
kind: signature
hmac: 8fdd8848540fde43d3dbe6c4e4b751bcb77965f10d73d37a4ba7aa85c4bd1a1b

...
