---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: format
  pull: never
  image: patwie/clang-format:latest
  commands:
    - ./.ci/check.sh

- name: cpplint
  pull: never
  image: patwie/cpplint:latest
  commands:
    - cpplint --recursive .

- name: compile
  image: patwie/cuda:latest
  pull: never
  commands:
    - mkdir build
    - cd build
    - cmake ..
    - make

- name: test
  image: patwie/cuda:latest
  pull: never
  commands:
    - ./build/test_cpu

---
kind: signature
hmac: dfdc7bd25d4cd1be5a2cd66aafe0051ed7cfb00971fa169d08d799731e8a0952

...
